CajaAhorro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from material.frontend import urls as frontend_urls
from core.views import Login, lx_logout, Index
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', Login.as_view(), name="login_caja"),
    url(r'^logout/$', lx_logout, name="logout"),
    url(r'^$', login_required(Index.as_view())),
    url(r'^control/', include('core.urls')),
    url(r'', include(frontend_urls)),
]

core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from views import Index, PersonasIndex

urlpatterns = [
    url(r'^$', login_required(Index.as_view()), name="index"),
    url(r'^persona/$', login_required(PersonasIndex.as_view()),
        name="index_persona"),
    ]

core/models.py
from __future__ import unicode_literals
from material.frontend.apps import ModuleMixin

from django.db import models


class Persona(models.Model):
    name = models.CharField(max_length=200, verbose_name='Nombre')
    last_name = models.CharField(max_length=200, verbose_name='Apellido')
    cedula = models.IntegerField(verbose_name='Cedula')
    email = models.EmailField(verbose_name='Correo')

    class Meta:
        verbose_name = "Persona"
        verbose_name_plural = "Personas"

    def __unicode__(self):
        return '%s %s' % (self.name, self.last_name)


class Caja(models.Model):
    title = models.CharField(max_length=200, verbose_name='Titulo')
    monto_numero = models.FloatField(verbose_name='Monto por Numero')
    monto_multa = models.FloatField(verbose_name='Monto por Multa')
    personas = models.ManyToManyField(Persona, verbose_name='Socios',
                                      related_name='socios')
    admins = models.ManyToManyField(Persona, verbose_name='Adminitradores',
                                    related_name='admins')
    close_date = models.DateField(verbose_name='Fecha de Cierre')
    date = models.DateField(auto_now_add=True,
                            verbose_name='Fecha de registro')

    class Meta:
        verbose_name = "Caja"
        verbose_name_plural = "Cajas"

    def __unicode__(self):
        return '%s' % (self.title)


class Numero(models.Model):
    persona = models.ForeignKey(Persona, verbose_name='Socio',
                                related_name='Socio')
    caja = models.ForeignKey(Caja, verbose_name='Caja de ahorro',
                             related_name='Caja_ahorro')
    date = models.DateField(auto_now_add=True,
                            verbose_name='Fecha de registro')

    class Meta:
        verbose_name = "Numero"
        verbose_name_plural = "Numeros"

    def __unicode__(self):
        return '%s %s' % (self.persona, self.caja)


class Prestamo(models.Model):
    persona = models.ForeignKey(Persona, verbose_name='Socio',
                                related_name='Socio_prestamo')
    caja = models.ForeignKey(Caja, verbose_name='Caja de ahorro',
                             related_name='Caja_ahorro_prestamo')
    date = models.DateField(auto_now_add=True,
                            verbose_name='Fecha de registro')
    monto = models.FloatField(verbose_name='Monto')

    class Meta:
        verbose_name = "Prestamo"
        verbose_name_plural = "Prestamos"

    def __unicode__(self):
        return '%s %s' % (self.persona, self.caja)

core/views.py
# -*- coding: utf-8 -*-
# from django.shortcuts import render
import json

from django.views.generic import TemplateView
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.models import User
from models import Persona


class Login(TemplateView):
    template_name = "login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(request.GET.get("next", False))
        return render_to_response(self.template_name, {},
                                  RequestContext(request))

    def post(self, request, *args, **kwargs):
        logout(request)
        next_ = request.GET['next'] if request.GET.get('next', False) else '/'
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        try:
            user = authenticate(
                    username=User.objects.get(email__iexact=email).username,
                    password=password)
        except:
            user = None
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(request.GET.get("next", False))
            else:
                resp = {'msj': "Contraseña valida, \
                                pero su Cuenta esta deshabilitada!.",
                        'error': True,
                        'url_redirect': False,
                        'icono': 'icon fa fa-warning',
                        'type': 'warning'}
        else:
            resp = {'msj': "Email o contraseña incorrectos.",
                    'error': True,
                    'url_redirect': False,
                    'icono': 'icon fa fa-ban',
                    'type': 'danger'}
        return render_to_response(self.template_name, {
                                        'resp': resp},
                                  RequestContext(request))


class Index(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        return render_to_response(self.template_name, {},
                                  RequestContext(request))


def lx_logout(request):
    try:
        logout(request)
    except:
        pass
    return HttpResponseRedirect('/')


class PersonasIndex(TemplateView):
    template_name = "persona/index.html"

    def get(self, request, *args, **kwargs):
        personas = Persona.objects.filter()
        return render_to_response(self.template_name, {
                                  'personas': personas
                                  },
                                  RequestContext(request))

core/templates/base_module.html
{% load i18n static %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" style="background-color:#eee">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
        <title>{% block title %}{% endblock %}</title>
        {% block favicon %}<link href="{% static 'imgs/favicon.jpg' %}" rel="shortcut icon">{% endblock %}
        {% block css %}
        <link href="{% static 'material/css/materialize.css' %}" rel="stylesheet">
        <link href="{% static 'material/css/jquery.datetimepicker.css ' %}" rel="stylesheet">
        <link href="{% static 'material/css/forms.css ' %}" rel="stylesheet">
        <link href="{% static 'material/frontend/css/frontend.css' %}" rel="stylesheet">
        <link href="{% static 'material/fonts/material-design-icons/material-icons.css' %}" rel="stylesheet">
        {% endblock %}

        {% block js %}
        <script src="{% static 'material/js/jquery-2.2.0.js' %}"></script>
        <script src="{% static 'material/js/materialize.js' %}"></script>
        <script src="{% static 'material/js/jquery.datetimepicker.js' %}"></script>
        <script src="{% static 'material/js/jquery.formset.js' %}"></script>
        <script src="{% static 'material/frontend/js/jquery.activeNavigation.js' %}"></script>
        <script src="{% static 'material/frontend/js/jquery.pjax.js' %}"></script>
        <script src="{% static 'material/js/material_init.js' %}"></script>
        <script src="{% static 'material/frontend/js/frontend.js' %}"></script>
        {% endblock %}

        {% block extrahead %}{% endblock %}
    </head>
    <body>
        {% if user.is_authenticated %}{% block user_menu %}{% include 'user_menu.html' %}{% endblock %}{% endif %}
        <header>
            <nav class="nav-top green">
                <a href="#" data-activates="nav-mobile" class="button-collapse full"><i class="material-icons">menu</i></a>

                <div class="nav-wrapper">
                    <div class="page-title hide-on-med-and-down">
                        {% block page_title %}<a href="/">{% trans "Viewflow" %}</a>{% endblock %}
                    </div>
                    
                    <ul class="right">
                        {% block top_menu_extra %}
                        {% endblock %}
                        {% block user_menu_dropdown %}
                          {% if user.is_authenticated %}
                            <li>
                              <a class="dropdown-button constrain_width" href="#!" data-activates="user-menu">
                              {{ user.get_full_name|default:user.username }}
                              <i class="material-icons right">arrow_drop_down</i></a>
                            </li>
                          {% else %}
                            <li><a href="{% url 'login_caja' %}" alt="Login"><i class="material-icons">lock</i></a></li>
                          {% endif %}
                        {% endblock %}
                    </ul>
                </div>
                <ul id="nav-mobile" class="side-nav fixed module-menu">
                    <li class="logo valign-wrapper">
                        <a href="/" class="no-navigation">{% block page_logo %}<img class="responsive-img" height="100" width="145" src="{% static 'imgs/logo.gif' %}">{% endblock %}</a>
                    </li>
                {% include 'menu.html' %}
                </ul>
            </nav>
        </header>
        <main>
            {% block main %}
            {% block breadcrumbs %}
            <div class="breadcrumbs">
                <div class="green darken-2 white-text">
                    {% block breadcrumbs_items %}
                    {% endblock %}
                </div>
            </div>
            {% endblock %}
            {% block content %}
            <div class="row">
            </div>
            {% endblock %}
            {% endblock %}

            {% block messages %}
            {% if messages %}
            <script type="text/javascript">
                $(document).ready(function() {
                    {% for message in messages %}
                        Materialize.toast('{{ message|capfirst }}', 10000, 'alert-{{ message.tags }}') 
                    {% endfor %}
                });
            </script>
            {% endif %}
            {% endblock %}
        </main>
        {% block load_indicator %}
        <div id="load_indicator" class="preloader-wrapper big active" style="position:absolute;left:45%;top:45%;display:none">
            <div class="spinner-layer spinner-blue-only">
                <div class="circle-clipper left"><div class="circle"></div></div>
                <div class="gap-patch"><div class="circle"></div></div>
                <div class="circle-clipper right"><div class="circle"></div></div>
            </div>
        </div>
        {% endblock %}
    </body>
</html> 

core/templates/index.html
{% extends 'base_module.html' %}
{% block title %}Inicio{% endblock title %}
{% block page_title %}
<a>Bienvenido</a>
{% endblock page_title %}

core/templates/login.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static material_form %}

{% block title %}login{% endblock title %}
{% block content %}
<div class="row">
    <div class="col s12 offset-m3 m6">
        <div class="card">
            <div class="card-content">
                <span class="card-title black-text">{% trans 'Log in' %}</span>
                <form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
                    <small class="error">
                        {{resp.msj}}
                    </small>
                    <div class="row">
                        <div class="input-field col s12 required">
                        <i class="mdi-action-account-box prefix"></i>
                        <input id="id_email" type="email" name="email">
                        <label for="id_email" class="active">Correo electronico</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 required">
                            <i class="mdi-action-lock prefix"></i>
                            <input id="id_password" type="password" name="password">
                            <label for="id_password" class="active">Contraseña</label>
                        </div>
                    </div>
                    <div class="card-action right-align">
                        <button type="submit" class="btn btn-primary">Iniciar sesion</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/menu.html
                  {% if user.is_authenticated %}
                    <li class="no-padding">
                        <div class="collapsible-body" style="display:block">
                            <ul class="collapsible" data-collapsible="accordion">
                                <li class="header active">
                                    <a href="{% url 'index_persona'%}" class="collapsible-header active">
                                    <i class="material-icons admin-appicon admin-appicon-auth"></i>
                                    Personas</a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="no-padding">
                        <a class="collapsible-header no-pjax" href="#">Cajas</a>
                    </li>
                    {% endif %}

core/templates/persona/index.html
{% extends 'base_module.html' %}
{% block title %}Personas Registradas{% endblock title %}
{% block page_title %}
<a>Gestion de personas</a>
{% endblock page_title %}
{% block content %}
<div class="row">
    <div class="col s12 m8 l12">
    	<div class="card data-card">
    		<div class="card-content">
		        <div class="results">
		            <div id="result_list_wrapper" class="dataTables_wrapper no-footer">
			            <table id="result_list" class="table bordered dataTable no-footer" role="grid">
			            	<thead>
			            <tr class="row1 odd" role="row">
			                	<th scope="col" class="sortable column-name sorting_disabled" rowspan="1" colspan="1">
			                        <span>Nombre</span>
			                	</th>
			                	<th scope="col" class="column-__str__ sorting_disabled" rowspan="1" colspan="1">
			                        <span>Apellido</span>
			                	</th>
			                	<th scope="col" class="column-__str__ sorting_disabled" rowspan="1" colspan="1">
			                        <span>Cedula</span>
			                	</th>
			                	<th scope="col" class="column-__str__ sorting_disabled" rowspan="1" colspan="1">
			                        <span>Email</span>
			                	</th>
			            </tr>
			        </thead>
			        <tbody>
				        {%for persona in personas %}
				        <tr class="row1 odd" role="row">
				        	<th><a href="#">{{persona.name}}</a></th>
				        	<td>{{persona.last_name}}</td>
				        	<td>{{persona.cedula}}</td>
				        	<td>{{persona.email}}</td>
				        </tr>
				        {% endfor %}
			        </tbody>
			        </table>
		            </div>
		        </div>
		        <div class="row">
			        <div class="col s12">
			        	<div class="col s12">
			        		<div class="right">
			        			<small>
			        				{{personas.count}} Persona
			        			</small>
			        		</div>
			        	</div>
			        </div>
		        </div>
    		</div>
		</div>
	</div>
</div>
<div class="fixed-action-btn">
	<a class="btn-floating btn-large waves-effect waves-light red z-depth-2" href="/admin/core/persona/add/">
		<i class="large material-icons">add</i>
	</a>
</div>
{% endblock %}

core/templates/user_menu.html
<ul id="user-menu" class="dropdown-content active">
    <li><a href="/logout/">Salir</a></li>
</ul>